spring:
  application:
    name: rocketmq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 192.168.56.106:9876
#        bindings:
#          input: {consumer.orderly: true}
      bindings:
        input: {destination: test-topic, content-type: application/json, group: test-group, consumer.maxAttempts: 1}

server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: '*'