server:
  port: 8081

spring:
  application:
    name: hello-security
  datasource:
    url: jdbc:mysql://localhost:3306/hello-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

