mybatis:
  jdbc:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&useSSL=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver: com.mysql.cj.jdbc.Driver
